version: "3.9"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
  web:
    build:
      context: "./"
      dockerfile: "./node.Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
